### PR TITLE
Make the codebase more beautiful

### PR DESCRIPTION
**Pull request by PoLaKoSz**
Hi!

I know, I know this is not so usefull just thought try to help with something. :smile:

I would like to ask can I format XAML codes with the `Ctrl + K + D` keycombination?

**WatchListView.xaml**
```` XML
<UserControl x:Class="MoodMovies.Views.WatchListView"
             x:Name="mlist"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             FontFamily="century gothic"
             mc:Ignorable="d" d:DesignHeight="450" d:DesignWidth="300" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
    <Grid x:Name="MainGrid" Focusable="True">
        <materialDesign:DialogHost>
            <materialDesign:DialogHost.DialogContent>
                <Grid Width="800" Height="400" Background="{StaticResource PrimaryHueDarkBrush}">

                </Grid>
            </materialDesign:DialogHost.DialogContent>
            <Grid>               
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="80"/>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="80"/>
                </Grid.ColumnDefinitions>
                <Button Grid.Column="0" x:Name="PreviousPage" VerticalAlignment="Center" HorizontalAlignment="Center" Background="Transparent" BorderBrush="Transparent"
                        Width="60" Height="60" HorizontalContentAlignment="Center" Foreground="{StaticResource SecondaryAccentBrush}">
                    <iconPacks:MaterialLight Kind="ChevronLeft" Width="30" Height="30"/>
                </Button>
                <ScrollViewer x:Name="MovieScrollViewer" Grid.Column="1" HorizontalScrollBarVisibility="Hidden" VerticalScrollBarVisibility="Hidden"
                      VerticalAlignment="Center" HorizontalAlignment="Center" Width="{Binding ElementName=MainGrid, Path=ActualWidth}" >
                    <ItemsControl x:Name="Movies">
                        <ItemsControl.ItemsPanel>
                            <ItemsPanelTemplate>
                                <WrapPanel MaxWidth="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type Window}}, Path=ActualWidth}" 
                                   VerticalAlignment="Center" HorizontalAlignment="Center"/>
                            </ItemsPanelTemplate>
                        </ItemsControl.ItemsPanel>
                    </ItemsControl>
                </ScrollViewer>
                <Button Grid.Column="2" x:Name="NextPage" VerticalAlignment="Center" HorizontalAlignment="Center" Background="Transparent" BorderBrush="Transparent"
                        Width="60" Height="60" HorizontalContentAlignment="Center" Foreground="{StaticResource SecondaryAccentBrush}">
                    <iconPacks:MaterialLight Kind="ChevronRight" Width="30" Height="30"/>
                </Button>
            </Grid>

            <!--{Binding ElementName=MovieScrollViewer, Path=ViewportWidth}"-->
        </materialDesign:DialogHost>
    </Grid>
</UserControl>
````
would become this:
```` XML
<UserControl x:Class="MoodMovies.Views.WatchListView"
             x:Name="mlist"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             FontFamily="century gothic"
             mc:Ignorable="d"
             d:DesignHeight="450"
             d:DesignWidth="300"
             HorizontalAlignment="Stretch"
             VerticalAlignment="Stretch">
    <Grid x:Name="MainGrid"
          Focusable="True">
        <materialDesign:DialogHost>
            <materialDesign:DialogHost.DialogContent>
                <Grid Width="800"
                      Height="400"
                      Background="{StaticResource PrimaryHueDarkBrush}">

                </Grid>
            </materialDesign:DialogHost.DialogContent>
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="80" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="80" />
                </Grid.ColumnDefinitions>
                <Button Grid.Column="0"
                        x:Name="PreviousPage"
                        VerticalAlignment="Center"
                        HorizontalAlignment="Center"
                        Background="Transparent"
                        BorderBrush="Transparent"
                        Width="60"
                        Height="60"
                        HorizontalContentAlignment="Center"
                        Foreground="{StaticResource SecondaryAccentBrush}">
                    <iconPacks:MaterialLight Kind="ChevronLeft"
                                             Width="30"
                                             Height="30" />
                </Button>
                <ScrollViewer x:Name="MovieScrollViewer"
                              Grid.Column="1"
                              HorizontalScrollBarVisibility="Hidden"
                              VerticalScrollBarVisibility="Hidden"
                              VerticalAlignment="Center"
                              HorizontalAlignment="Center"
                              Width="{Binding ElementName=MainGrid, Path=ActualWidth}">
                    <ItemsControl x:Name="Movies">
                        <ItemsControl.ItemsPanel>
                            <ItemsPanelTemplate>
                                <WrapPanel MaxWidth="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type Window}}, Path=ActualWidth}"
                                           VerticalAlignment="Center"
                                           HorizontalAlignment="Center" />
                            </ItemsPanelTemplate>
                        </ItemsControl.ItemsPanel>
                    </ItemsControl>
                </ScrollViewer>
                <Button Grid.Column="2"
                        x:Name="NextPage"
                        VerticalAlignment="Center"
                        HorizontalAlignment="Center"
                        Background="Transparent"
                        BorderBrush="Transparent"
                        Width="60"
                        Height="60"
                        HorizontalContentAlignment="Center"
                        Foreground="{StaticResource SecondaryAccentBrush}">
                    <iconPacks:MaterialLight Kind="ChevronRight"
                                             Width="30"
                                             Height="30" />
                </Button>
            </Grid>

            <!--{Binding ElementName=MovieScrollViewer, Path=ViewportWidth}"-->
        </materialDesign:DialogHost>
    </Grid>
</UserControl>
````

### CODE REVIEW

**Comment by tonykaralis** [comment]
Hey friend, all help is useful. This looks good. I will merge when I get to my laptop 👍 thanks alot. After this I will have a think and see if there is something more challenging and interesting for you to work on. If you are keen of course.

**Comment by PoLaKoSz** [comment]
Thank You!

Currently I fight with XAML Styles so if You think you can wait with the merge I will push addition commit(s) to this PR later (hope soon).

Also I wanted to ask in the future if I open a PR should I open it only if I know I won't want to push additional commit?

**Comment by tonykaralis** [comment]
1. Yes I will wait for you to finish all commits to this PR before I merge. No rush, let me know when you are finished.
2. Usually you open a pull request when you are finished, but many times you may need to add more commits after(code review etc). My advise would be to open PR only when you are ready. Usually if i see a pull request, I will read comments first, then review. If comments lead to more commits then no problem. 
3. You can format xaml, it looks better 👍 
4. I will try and take a look at app.xaml as soon as I can. Maybe only monday. 

Thanks again for the help.

**Comment by PoLaKoSz** [comment]
Thank You for the advice I will keep in my mind.

**Comment by tonykaralis** [comment]
Hi Tom, Is this branch ready for merging?

**Comment by PoLaKoSz** [comment]
Hi!

I wasn't able to crack why the styles not working so I just pushed this last commit to format the XAML code. If it looks good to You I won't commit into this PR.

**Comment by tonykaralis** [comment]
Thanks mate. It had some merge conflicts but those were my fault 🚶

**Pull request merged**
